namespace MortarHUD.Localization;

/// <summary>
/// 中英文文案表。键由 <c>_analysis/gen-loc-table.py</c> 生成，两张表必须成对。
/// </summary>
/// <remarks>
/// 这个文件是生成的，但可以手工改英文——改完不用重跑脚本，脚本只在新增文案时用。
/// </remarks>
public static class Strings
{
    private static readonly Dictionary<string, (string Zh, string En)> Table = new(StringComparer.Ordinal)
    {
        ["Repaired"] = ("   修正文本: {0}", "   Repaired: {0}"),
        ["Raw"] = ("   原始文本: {0}", "   Raw: {0}"),
        ["Empty"] = ("(空)", "(empty)"),
        ["XPointsEast"] = ("+X 指向东（East）", "+X points East"),
        ["YPointsNorth"] = ("+Y 指向北（North）", "+Y points North"),
        ["OpenTheMapAndLockTheGun"] = ("01   开图并锁定炮位", "01   Open the map and lock the gun"),
        ["PointAtTheTargetAndPressTheTargetKey"] = ("02   指向目标，按记录目标键", "02   Point at the target and press the target key"),
        ["ReadAZAndRNGFromTheHUD"] = ("03   查看 HUD 方位与距离", "03   Read AZ and RNG from the HUD"),
        ["TestingIn3SecondsAndSavingImages"] = ("3 秒后测试并保存图片", "Testing in 3 seconds and saving images"),
        ["CAPTUREFAILEDCannotReadTheCursorPosition"] = ("CAPTURE_FAILED: 无法读取光标位置", "CAPTURE_FAILED: cannot read the cursor position"),
        ["DebugMode"] = ("Debug 模式", "Debug mode"),
        ["GetDCDesktopFailedTheScreenIsNotAccessible"] = ("GetDC(桌面) 失败，无法访问屏幕。", "GetDC(desktop) failed; the screen is not accessible."),
        ["HUDUnlockedDragItOnScreenToMoveItUncheckToRestor"] = ("HUD 已解锁：直接拖动屏幕上的 HUD 调整位置，调好后取消勾选即可恢复鼠标穿透。", "HUD unlocked: drag it on screen to move it. Uncheck to restore click-through."),
        ["HUDLockedClickThroughRestored"] = ("HUD 已锁定，恢复鼠标穿透。", "HUD locked; click-through restored."),
        ["HUDPreview"] = ("HUD 预览", "HUD preview"),
        ["MAutoCalibrationOnlyFiresWhileTheCursorIsBackAtT"] = ("M 在光标回中后短时连拍，连续两帧一致才记录；连拍结束后可移动光标。", "M captures a short burst after the cursor recenters and requires two matching frames. You can move the cursor after the burst."),
        ["MortarHUDMortarCoordinateSolver"] = ("MortarHUD —— 迫击炮坐标解算", "MortarHUD — mortar coordinate solver"),
        ["MortarHUDCrosshair"] = ("MortarHUD 准星", "MortarHUD crosshair"),
        ["MortarHUDSelfTest"] = ("MortarHUD 启动自检", "MortarHUD self-test"),
        ["MortarHUDIsAlreadyRunningOpenSettingsFromTheSyst"] = ("MortarHUD 已经在运行了，请从系统托盘打开设置。", "MortarHUD is already running. Open settings from the system tray."),
        ["MortarHUDSettings"] = ("MortarHUD 设置", "MortarHUD Settings"),
        ["MortarHUDDebugPanel"] = ("MortarHUD 调试面板", "MortarHUD debug panel"),
        ["MortarHUDError"] = ("MortarHUD 遇到错误", "MortarHUD error"),
        ["OCREngine"] = ("OCR 引擎", "OCR engine"),
        ["TheROIIsEmptyThereIsNothingToProcess"] = ("ROI 为空，没有可处理的像素。", "The ROI is empty; there is nothing to process."),
        ["InvalidROISizeX"] = ("ROI 尺寸非法：{0}x{1}。", "Invalid ROI size: {0}x{1}."),
        ["TessdataPath"] = ("Tessdata 路径", "Tessdata path"),
        ["TesseractFailedToInitializeTessdataPath"] = ("Tesseract 初始化失败：{0}（tessdata 路径：{1}）", "Tesseract failed to initialize: {0} (tessdata path: {1})"),
        ["WARDOGSMortarCoordinateSolver"] = ("WARDOGS · 迫击炮坐标解算", "WARDOGS · mortar coordinate solver"),
        ["TessdataDirectoryNotFound"] = ("tessdata 目录不存在：{0}", "tessdata directory not found: {0}"),
        ["HasMoreThanOneMainKeyAHotkeyTakesExactlyOne"] = ("「{0}」里有多个主键，一个热键只能有一个主键。", "\"{0}\" has more than one main key; a hotkey takes exactly one."),
        ["HasNoMainKey"] = ("「{0}」里没有主键。", "\"{0}\" has no main key."),
        ["Opacity"] = ("不透明度", "Opacity"),
        ["BothGlyphImagesMustHaveTheSameSize"] = ("两张字形图的尺寸必须一致。", "Both glyph images must have the same size."),
        ["Primary"] = ("主色", "Primary"),
        ["TheThemeNameCannotBeEmpty"] = ("主题名不能为空。", "The theme name cannot be empty."),
        ["ThemeDeleted"] = ("主题已删除。", "Theme deleted."),
        ["ThemeImported"] = ("主题已导入。", "Theme imported."),
        ["ThemeExportedTo"] = ("主题已导出到 {0}", "Theme exported to {0}"),
        ["AThemeMustHaveAName"] = ("主题必须有名字。", "A theme must have a name."),
        ["ThemePresets"] = ("主题预设", "Theme presets"),
        ["PickAColorFromThePalette"] = ("从调色板选一个颜色", "Pick a color from the palette"),
        ["StartFromAPresetThePreviewOnTheRightUpdatesLive"] = ("从预设开始，右侧实时预览显示效果。", "Start from a preset; the preview on the right updates live."),
        ["Position"] = ("位置", "Position"),
        ["HowToUse"] = ("使用顺序", "How to use"),
        ["UsePreset"] = ("使用预设", "Use preset"),
        ["UseDefaults"] = ("使用默认设置", "Use defaults"),
        ["SaveRawROI"] = ("保存原始 ROI", "Save raw ROI"),
        ["SaveClose"] = ("保存并收起", "Save & close"),
        ["SavePreprocessedResult"] = ("保存预处理结果", "Save preprocessed result"),
        ["KeepTheEvidenceFindTheCause"] = ("保留证据，找到原因。", "Keep the evidence, find the cause."),
        ["OffsetX"] = ("偏移 X", "Offset X"),
        ["OffsetY"] = ("偏移 Y", "Offset Y"),
        ["OccasionalReadFailures"] = ("偶尔识别失败？", "Occasional read failures?"),
        ["Cursor"] = ("光标      {0}, {1}", "Cursor    {0}, {1}"),
        ["CursorMovedCancelled"] = ("光标移动，已取消", "Cursor moved, cancelled"),
        ["Close"] = ("关闭", "Close"),
        ["ClosingTheWindowKeepsMortarHUDRunningInTheSystem"] = ("关闭窗口后，程序继续在系统托盘运行。", "Closing the window keeps MortarHUD running in the system tray."),
        ["BuiltInThemeCannotBeDeletedUseSaveAsFirst"] = ("内置主题「{0}」不能删除，可以先「另存为」再改。", "Built-in theme \"{0}\" cannot be deleted. Use \"Save as\" first."),
        ["BuiltInThemeCannotBeRenamed"] = ("内置主题「{0}」不能改名。", "Built-in theme \"{0}\" cannot be renamed."),
        ["BuiltInThemesCannotBeRenamedUseSaveAsFirst"] = ("内置主题不能改名。可以先「另存为」再改。", "Built-in themes cannot be renamed. Use \"Save as\" first."),
        ["ABuiltInThemeCannotBeOverwrittenUseSaveAs"] = ("内置主题不能覆盖保存，请用「另存为」。", "A built-in theme cannot be overwritten. Use \"Save as\"."),
        ["AutoCalibrationNotReady"] = ("未取得稳定炮位", "Gun position not stable"),
        ["AutoCalibrationRetryHint"] = ("炮位 / 目标未改变 · 可手动记录炮位", "Gun / target unchanged · Record the gun manually if needed"),
        ["PressMAgain"] = ("再按一次 M", "Press M again"),
        ["FailedToWriteTheDebugResult"] = ("写入 Debug 结果失败：{0}", "Failed to write the debug result: {0}"),
        ["ToggleHUD"] = ("切换 HUD", "Toggle HUD"),
        ["Delete"] = ("删除", "Delete"),
        ["DeleteFailed"] = ("删除失败。", "Delete failed."),
        ["SemiBold"] = ("半粗体", "SemiBold"),
        ["OneShotRecognitionTest"] = ("单次识别测试", "One-shot recognition test"),
        ["RawROI"] = ("原始 ROI", "Raw ROI"),
        ["FatalErrorTheApplicationWillExit"] = ("发生致命错误，程序即将退出", "Fatal error; the application will exit"),
        ["Cancel"] = ("取消", "Cancel"),
        ["SaveAs"] = ("另存为…", "Save as…"),
        ["SaveAsTheme"] = ("另存为主题", "Save as theme"),
        ["OnlyTheSmallAreaAroundTheCursorIsSavedAllDiagnos"] = ("只保存光标附近的小块画面，所有诊断文件留在本机。", "Only the small area around the cursor is saved; all diagnostic files stay on this machine."),
        ["Right"] = ("右对齐", "Right"),
        ["Pipelines"] = ("各流水线：", "Pipelines:"),
        ["StartupFailed"] = ("启动失败", "Startup failed"),
        ["StartMinimizedToTray"] = ("启动时最小化到托盘", "Start minimized to tray"),
        ["Startup"] = ("启动行为", "Startup"),
        ["EnableDebugMode"] = ("启用 Debug 模式", "Enable debug mode"),
        ["MapNotOpen"] = ("地图没打开", "Map not open"),
        ["MapKey"] = ("地图键", "Map key"),
        ["FailedToListenForTheMapKey"] = ("地图键监听失败。", "Failed to listen for the map key."),
        ["MapKeyAutoCalibration"] = ("地图键自动校准", "Map-key auto calibration"),
        ["AutoCalibrateTheGunFromTheMapKey"] = ("地图键自动校准炮位", "Auto-calibrate the gun from the map key"),
        ["CoordinateConversion"] = ("坐标换算", "Coordinate conversion"),
        ["CoordinateConversionAndAxes"] = ("坐标换算与轴向", "Coordinate conversion and axes"),
        ["CoordinateMax"] = ("坐标最大值", "Coordinate max"),
        ["CoordinateMin"] = ("坐标最小值", "Coordinate min"),
        ["CoordinateOutOfRange"] = ("坐标超出范围", "Coordinate out of range"),
        ["AxisDirections"] = ("坐标轴方向", "Axis directions"),
        ["BaselineSampling"] = ("基准采样", "Baseline sampling"),
        ["Appearance"] = ("外观", "Appearance"),
        ["SizeAndLayout"] = ("大小与布局", "Size and layout"),
        ["ErrorColor"] = ("失败色", "Error color"),
        ["Font"] = ("字体", "Font"),
        ["FontColorAndEffects"] = ("字体、颜色与特效", "Font, color and effects"),
        ["FontSize"] = ("字号", "Font size"),
        ["GlyphTemplates"] = ("字形模板", "Glyph templates"),
        ["Weight"] = ("字重", "Weight"),
        ["LetterSpacing"] = ("字间距", "Letter spacing"),
        ["LivePreview"] = ("实时预览", "Live preview"),
        ["Width"] = ("宽度", "Width"),
        ["Alignment"] = ("对齐", "Alignment"),
        ["Import"] = ("导入…", "Import…"),
        ["ImportTheme"] = ("导入主题", "Import theme"),
        ["ImportFailed"] = ("导入失败。", "Import failed."),
        ["Export"] = ("导出…", "Export…"),
        ["ExportTheme"] = ("导出主题", "Export theme"),
        ["ExportFailed"] = ("导出失败。", "Export failed."),
        ["NotTestedYetTheCursorMustBePointingAtTheCoordina"] = ("尚未测试。当前光标必须指向游戏中的坐标读数。", "Not tested yet. The cursor must be pointing at the coordinate readout in game."),
        ["UnexpectedErrorDuringScreenCapture"] = ("屏幕捕获发生未预期错误。", "Unexpected error during screen capture."),
        ["TopLeft"] = ("左上", "Top left"),
        ["BottomLeft"] = ("左下", "Bottom left"),
        ["Left"] = ("左对齐", "Left"),
        ["SavedCustomTheme"] = ("已保存自定义主题「{0}」。", "Saved custom theme \"{0}\"."),
        ["AppliedAt"] = ("已应用（{0:HH:mm:ss}）。", "Applied at {0:HH:mm:ss}."),
        ["EnabledTheNext10CapturesWillSaveFullDiagnosticsG"] = ("已开启：接下来 10 次采集保存完整诊断。返回游戏后按热键复现即可。", "Enabled: the next 10 captures will save full diagnostics. Go back to the game and reproduce with the hotkey."),
        ["Rendered"] = ("已渲染 {0}", "Rendered {0}"),
        ["OverwroteTheme"] = ("已覆盖保存主题「{0}」。", "Overwrote theme \"{0}\"."),
        ["Layout"] = ("布局", "Layout"),
        ["CommonColors"] = ("常用色", "Common colors"),
        ["Regular"] = ("常规", "Regular"),
        ["Apply"] = ("应用", "Apply"),
        ["ApplyFailed"] = ("应用失败：{0}", "Apply failed: {0}"),
        ["AfterEnablingGoBackToTheGameAndReproduceWithTheH"] = ("开启收集后回到游戏，正常按热键复现。接下来 10 次采集会保存原图、预处理图和识别结果，然后自动停止临时收集。", "After enabling, go back to the game and reproduce with the hotkey. The next 10 captures save the raw image, the preprocessed images and the result, then collection stops automatically."),
        ["StartWithWindows"] = ("开机自动启动", "Start with Windows"),
        ["FailedToChangeTheStartWithWindowsSetting"] = ("开机自启设置失败", "Failed to change the start-with-Windows setting"),
        ["EngineAndPreprocessing"] = ("引擎与预处理", "Engine and preprocessing"),
        ["RequireADecimalPoint"] = ("必须识别出小数点", "Require a decimal point"),
        ["MasterSwitch"] = ("总开关", "Master switch"),
        ["RestoreDefaults"] = ("恢复默认", "Restore defaults"),
        ["SuccessColor"] = ("成功色", "Success color"),
        ["CaptureFailed"] = ("截图失败", "Capture failed"),
        ["OpenDebugFolder"] = ("打开 Debug 目录", "Open debug folder"),
        ["WaitAfterOpeningTheMap"] = ("打开地图后等待", "Wait after opening the map"),
        ["UseItWithTheInGameMapOpenAFailedReadLeavesTheSav"] = ("打开游戏地图后操作。识别失败时，已保存的炮位与目标保持不变。", "Use it with the in-game map open. A failed read leaves the saved gun and target untouched."),
        ["FailedToOpenTheFolder"] = ("打开目录失败：{0}", "Failed to open the folder: {0}"),
        ["OpenSettings"] = ("打开设置", "Open settings"),
        ["OpenDiagnosticsFolder"] = ("打开诊断目录", "Open diagnostics folder"),
        ["OpenSampleFolder"] = ("打开采样目录", "Open sample folder"),
        ["OngoingDebugAndHUDDiagnostics"] = ("持续调试与 HUD 调试信息", "Ongoing debug and HUD diagnostics"),
        ["ScaleWithResolution"] = ("按分辨率自动缩放", "Scale with resolution"),
        ["AutoCalibrateTheGunWhenTheMapKeyIsPressed"] = ("按地图键自动校准炮位", "Auto-calibrate the gun when the map key is pressed"),
        ["OutlineThickness"] = ("描边粗细", "Outline thickness"),
        ["OutlineColor"] = ("描边色", "Outline color"),
        ["Hotkeys"] = ("操作按键", "Hotkeys"),
        ["AcceptsRRGGBBAARRGGBBAndRRGGBBAARRGGBB"] = ("支持 #RRGGBB、#AARRGGBB，也支持 RRGGBB / AARRGGBB", "Accepts #RRGGBB, #AARRGGBB, and RRGGBB / AARRGGBB"),
        ["Collapse"] = ("收起", "Collapse"),
        ["CollectTheNext10Captures"] = ("收集接下来 10 次采集", "Collect the next 10 captures"),
        ["OverallOpacity"] = ("整体不透明度", "Overall opacity"),
        ["TheFileContainsNoValidTheme"] = ("文件里没有有效的主题。", "The file contains no valid theme."),
        ["TextOutline"] = ("文字描边", "Text outline"),
        ["NewThemeName"] = ("新主题名称：", "New theme name:"),
        ["NewName"] = ("新名称：", "New name:"),
        ["AzimuthDecimals"] = ("方位角小数位", "Azimuth decimals"),
        ["CannotDetermineTheApplicationSOwnPath"] = ("无法确定程序自身的路径。", "Cannot determine the application's own path."),
        ["DailyUse"] = ("日常使用", "Daily use"),
        ["ShowHideHUD"] = ("显示 / 隐藏 HUD", "Show / hide HUD"),
        ["ShowAZ"] = ("显示 AZ", "Show AZ"),
        ["ShowHUD"] = ("显示 HUD", "Show HUD"),
        ["ShowRawOCRText"] = ("显示 OCR 原始文本", "Show raw OCR text"),
        ["ShowRNG"] = ("显示 RNG", "Show RNG"),
        ["ShowROIRectangle"] = ("显示 ROI 矩形", "Show ROI rectangle"),
        ["ShowCursorAnchor"] = ("显示光标锚点", "Show cursor anchor"),
        ["WhatToShow"] = ("显示内容", "What to show"),
        ["ContentAndPrecision"] = ("显示内容与精度", "Content and precision"),
        ["ShowGun"] = ("显示炮位", "Show gun"),
        ["ShowTarget"] = ("显示目标", "Show target"),
        ["ShowConfidence"] = ("显示置信度", "Show confidence"),
        ["ShowTiming"] = ("显示耗时", "Show timing"),
        ["ShowParsedCoordinates"] = ("显示解析后的坐标", "Show parsed coordinates"),
        ["MinimumConfidence"] = ("最低置信度", "Minimum confidence"),
        ["UnknownCause"] = ("未知原因", "Unknown cause"),
        ["NoGunRecorded"] = ("未记录炮位", "No gun recorded"),
        ["RawROIOfThisRun"] = ("本次原始 ROI", "Raw ROI of this run"),
        ["NoRawImageWasSavedForThisRunEnableDiagnosticColl"] = ("本次未保存原图，请先开启诊断收集", "No raw image was saved for this run; enable diagnostic collection first"),
        ["BuildTheOCRCapturePipeline"] = ("构建 OCR / 采集链路", "Build the OCR / capture pipeline"),
        ["CreateTheDebugPanelWindow"] = ("构造 Debug 面板窗口", "Create the debug panel window"),
        ["CreateTheHUDOverlayWindow"] = ("构造 HUD Overlay 窗口", "Create the HUD overlay window"),
        ["CreateTheHUDController"] = ("构造 HUD 控制器", "Create the HUD controller"),
        ["CreateTheTrayIconHidden"] = ("构造托盘图标（不显示）", "Create the tray icon (hidden)"),
        ["CreateTheSettingsWindowAll3PagesHUDPreview"] = ("构造设置窗口（含全部 4 个页面与 HUD 预览）", "Create the settings window (all 4 pages + HUD preview)"),
        ["CreateTheSettingsViewModel"] = ("构造设置视图模型", "Create the settings view model"),
        ["Soft"] = ("柔和", "Soft"),
        ["InspectASingleRecognition"] = ("查看单次识别结果", "Inspect a single recognition"),
        ["ValidationThresholds"] = ("校验阈值", "Validation thresholds"),
        ["TheTemplateCountDoesNotMatchTheBitmapCount"] = ("模板条数与位图数量不一致。", "The template count does not match the bitmap count."),
        ["Secondary"] = ("次级色", "Secondary"),
        ["MetersPerCoordinateUnit"] = ("每个坐标单位 =", "Meters per coordinate unit ="),
        ["MetersPerCoordinateUnitMustBeAPositiveFiniteNumb"] = ("每坐标单位的米数必须是正有限数。", "Meters per coordinate unit must be a positive finite number."),
        ["AlsoSaveTheFullScreenCursorPositionOnEveryCaptur"] = ("每次采集额外保存整屏 + 光标位置", "Also save the full screen + cursor position on every capture"),
        ["TextMs"] = ("毫秒", "ms"),
        ["NoThemeIsSelected"] = ("没有选中主题。", "No theme is selected."),
        ["TestFailed"] = ("测试出错：{0}", "Test failed: {0}"),
        ["CrispWithoutBeingLoud"] = ("清楚，不抢眼。", "Crisp without being loud."),
        ["Gun"] = ("炮位", "Gun"),
        ["GunLocked"] = ("炮位已锁定", "Gun locked"),
        ["ClickAHotkeyBoxThenPressTheNewKeyAfterPressingMK"] = ("点击键位框后按新键。按 M 后保持光标不动；未归位时可用手动炮位键。", "Click a hotkey box, then press the new key. After pressing M keep the cursor still; if it does not recenter, use the manual gun key."),
        ["TheHotkeyIsEmpty"] = ("热键为空。", "The hotkey is empty."),
        ["HotkeysRestoredToDefaultsClickApplyToTakeEffect"] = ("热键已恢复默认，点「应用」后生效。", "Hotkeys restored to defaults. Click Apply to take effect."),
        ["TheHotkeyOperationFailedOnTheMessageThread"] = ("热键操作在消息线程上失败。", "The hotkey operation failed on the message thread."),
        ["TheHotkeyIsNotSet"] = ("热键未设置。", "The hotkey is not set."),
        ["HotkeyRegistrationFailed"] = ("热键注册失败", "Hotkey registration failed"),
        ["TheHotkeyMessageWindowIsNotReady"] = ("热键消息窗口未就绪。", "The hotkey message window is not ready."),
        ["TheHotkeyMessageThreadDidNotRespondWithin5Second"] = ("热键消息线程 5 秒内没有响应，注册未生效。这通常意味着输入线程被卡住了。", "The hotkey message thread did not respond within 5 seconds, so registration did not take effect. This usually means the input thread is stuck."),
        ["ScreenCaptureMayNotWorkInExclusiveFullscreenUseB"] = ("独占全屏模式下屏幕捕获可能不可用，请改用无边框窗口模式。", "Screen capture may not work in exclusive fullscreen. Use borderless windowed mode instead."),
        ["UsedToCalibrateTheDefaultROITheFullScreenAndTheC"] = ("用来标定 ROI 默认值。整屏和光标在同一时刻记录，事后能量出坐标文字相对光标的准确方位——只看 ROI 推不出来。此项独立于上面的 Debug 总开关，采样文件在 Samples 子目录。", "Used to calibrate the default ROI. The full screen and the cursor are recorded at the same instant, so the exact position of the coordinate text relative to the cursor can be measured afterwards — the ROI alone cannot tell you that. This is independent of the debug master switch above; samples go to the Samples subfolder."),
        ["LeaveEmptyToUseModelsTessdataNextToTheExecutable"] = ("留空表示使用程序目录下的 Models\\tessdata", "Leave empty to use Models\\tessdata next to the executable"),
        ["Target"] = ("目标", "Target"),
        ["TargetLocked"] = ("目标已锁定", "Target locked"),
        ["TargetUnchanged"] = ("目标未改变", "Target unchanged"),
        ["Hard"] = ("硬边", "Hard"),
        ["TextOK"] = ("确定", "OK"),
        ["DeleteTheTheme"] = ("确定要删除主题「{0}」吗？", "Delete the theme \"{0}\"?"),
        ["SampleCoordinatesAppliedInGameAfterSaving"] = ("示例坐标 · 保存后应用到游戏", "Sample coordinates · applied in game after saving"),
        ["OffscreenRenderFailed"] = ("离屏渲染失败：{0}", "Offscreen render failed: {0}"),
        ["ManageCustomThemes"] = ("管理自定义主题", "Manage custom themes"),
        ["TextM"] = ("米", "m"),
        ["Bold"] = ("粗体", "Bold"),
        ["ExactPosition"] = ("精确位置", "Exact position"),
        ["Light"] = ("细体", "Light"),
        ["Background"] = ("背景", "Background"),
        ["BackgroundOpacity"] = ("背景不透明度", "Background opacity"),
        ["BackgroundColor"] = ("背景色", "Background color"),
        ["Auto"] = ("自动", "Auto"),
        ["Custom"] = ("自定义主题", "Custom"),
        ["SelfTestPassed"] = ("自检通过。", "Self-test passed."),
        ["AtLeastOneUsableOCREngineIsRequired"] = ("至少要有一个可用的 OCR 引擎。", "At least one usable OCR engine is required."),
        ["AtLeastOnePreprocessingPipelineIsRequired"] = ("至少要有一条预处理流水线。", "At least one preprocessing pipeline is required."),
        ["SavedToDisk"] = ("落盘", "Saved to disk"),
        ["LineHeight"] = ("行距", "Line height"),
        ["Overwrite"] = ("覆盖保存", "Overwrite"),
        ["UnlockThePositionAndDragTheHUD"] = ("解锁位置，拖动 HUD", "Unlock the position and drag the HUD"),
        ["WarningColor"] = ("警告色", "Warning color"),
        ["RecordGun"] = ("记录炮位", "Record gun"),
        ["RecordTarget"] = ("记录目标", "Record target"),
        ["RecordTarget2"] = ("记录目标（{0}）", "Record target ({0})"),
        ["SettingsTakeEffectAfterYouClickApply"] = ("设置在点击应用后生效。", "Settings take effect after you click Apply."),

        // 下面几条是手工加的：文案表由脚本生成，但加条目不必重跑脚本。
        // 键里没有对应英文（"Language" 不是译文），改手写反而更清楚。
        ["Language"] = ("语言", "Language"),
        ["LanguageHint"] = ("界面语言。切换后需要重启程序才会生效。",
                            "Interface language. Restarting the app is required to apply a change."),
        ["RecognitionAdvanced"] = ("识别参数（高级）", "Recognition (advanced)"),
        ["RecognitionFailed"] = ("识别失败", "Recognition failed"),
        ["RecognitionResult"] = ("识别结果", "Recognition result"),
        ["Diagnostics"] = ("诊断", "Diagnostics"),
        ["PressAKeyOrMouseButton"] = ("请按键或鼠标键…", "Press a key or mouse button…"),
        ["RunOneEndToEndRecognition"] = ("跑一次端到端识别", "Run one end-to-end recognition"),
        ["Range"] = ("距离", "Range"),
        ["ThisKeyIsNotSupported"] = ("这个键不支持", "This key is not supported"),
        ["ThisCanOnlyBeBoundToASingleKeyboardKeyWithNoModi"] = ("这个键只能绑定单个键盘按键（不带修饰键）。", "This can only be bound to a single keyboard key (with no modifiers)."),
        ["Exit"] = ("退出", "Exit"),
        ["BeforeTheCapture"] = ("采集前", "before the capture"),
        ["AfterTheCapture"] = ("采集后", "after the capture"),
        ["Rename"] = ("重命名…", "Rename…"),
        ["RenameTheme"] = ("重命名主题", "Rename theme"),
        ["RenameFailed"] = ("重命名失败。", "Rename failed."),
        ["ResetPosition"] = ("重置位置", "Reset position"),
        ["LockHUDPosition"] = ("锁定 HUD 位置", "Lock HUD position"),
        ["LockTheGunRecordTheTarget"] = ("锁定炮位，记录目标。", "Lock the gun, record the target."),
        ["Anchor"] = ("锚点", "Anchor"),
        ["Shadow"] = ("阴影", "Shadow"),
        ["ShadowColor"] = ("阴影色", "Shadow color"),
        ["UnhandledExceptionOnANonUIThreadTheProcessWillEx"] = ("非 UI 线程未处理异常，进程即将结束", "Unhandled exception on a non-UI thread; the process will exit"),
        ["Preprocessed"] = ("预处理", "Preprocessed"),
        ["PreprocessedResult"] = ("预处理结果", "Preprocessed result"),
        ["Height"] = ("高度", "Height"),
        ["MiddleMouse"] = ("鼠标中键", "Middle mouse"),
        ["MouseButton4"] = ("鼠标侧键 1", "Mouse button 4"),
        ["MouseButton5"] = ("鼠标侧键 2", "Mouse button 5"),
        ["RightMouse"] = ("鼠标右键", "Right mouse"),
        ["LeftMouse"] = ("鼠标左键", "Left mouse"),
        ["MouseHotkeysAndTheMapKeyWillBeUnavailable"] = ("鼠标热键与地图键将不可用", "Mouse hotkeys and the map key will be unavailable"),
        ["CursorInsideTheROI"] = ("鼠标相对 ROI", "Cursor inside the ROI"),
        ["NotSet"] = ("（未设置）", "(not set)"),
        ["Empty2"] = ("（空）", "(empty)"),
    };

    public static string Lookup(string key, string language)
    {
        // 漏翻一条不该让程序起不来：取不到就回落中文，再取不到就把键名原样返回，
        // 这样界面上会出现一个明显的占位串，比空白更容易发现。
        if (!Table.TryGetValue(key, out var entry))
        {
            return key;
        }

        return language == Loc.English && !string.IsNullOrEmpty(entry.En) ? entry.En : entry.Zh;
    }

    public static IReadOnlyDictionary<string, (string Zh, string En)> All => Table;
}
